### ISSUE TITLE
What is the data source?

### ISSUE THREAD

**Issue by PWPiranha** [kjhealy/us_elections_2020_csv#1]
Hi. Many Thanks for creating and sharing this file!! What is the source of this info? I am assuming it is collected from one of the major news organizations...but can't be certain. If I want to cite this data on a blog post (or some other informal venue), how do I do it?

**Comment by kjhealy** [comment]
The data are scraped from the BBC; the ultimate source is Reuters wire service. It's the same data that all the main media outlets use.
