### ISSUE TITLE
minor data problems

### ISSUE THREAD

**Issue by davidkane9** [kjhealy/us_elections_2020_csv#4]
I don't think `id` should be a state name like Iowa.

``` r
library(tidyverse)

read_csv("https://raw.githubusercontent.com/kjhealy/us_elections_2020_csv/master/results_x2020_11_07_08_13_28.csv", 
              col_types = cols(race = col_character(),
                               fips_char = col_character(),
                               place = col_character(),
                               id = col_character(),
                               fname = col_character(),
                               lname = col_character(),
                               party = col_character(),
                               pab = col_character(),
                               votes = col_double(),
                               incumbent = col_double(),
                               mpc = col_double())) %>% 
    filter(race != "House", nchar(id) == 4)
#> # A tibble: 4 x 12
#>   race  id    fips_char fips5 place fname lname party pab   votes incumbent
#>   <chr> <chr> <chr>     <chr> <chr> <chr> <chr> <chr> <chr> <dbl>     <dbl>
#> 1 Gove… Iowa  19        <NA>  <NA>  <NA>  <NA>  <NA>  <NA>     NA        NA
#> 2 Sena… Ohio  39        <NA>  <NA>  <NA>  <NA>  <NA>  <NA>     NA        NA
#> 3 Gove… Ohio  39        <NA>  <NA>  <NA>  <NA>  <NA>  <NA>     NA        NA
#> 4 Sena… Utah  49        <NA>  <NA>  <NA>  <NA>  <NA>  <NA>     NA        NA
#> # … with 1 more variable: mpc <dbl>
```

<sup>Created on 2020-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kjhealy** [comment]
I don't think `nchar()` is doing what you think it's doing there. Data for those states and races is certainly in the dataset. E.g.:

    library(tidyverse)
    read_csv("https://raw.githubusercontent.com/kjhealy/us_elections_2020_csv/master/results_x2020_11_07_08_13_28.csv",  
             col_types = cols(race = col_character(),
                              id = col_character(),
                              fips_char = col_character(),
                              fips5 = col_character(),
                              place = col_character(),
                              fname = col_character(),
                              lname = col_character(),
                              party = col_character(),
                              pab = col_character(), 
                              votes = col_integer(),
                              incumbent = col_integer(),
                              mpc = col_integer())) %>% 
      filter(race != "House", place %in% c("Ohio", "Utah", "Iowa"))
    #> # A tibble: 34 x 12
    #>    race  id    fips_char fips5 place fname lname party pab    votes incumbent
    #>    <chr> <chr> <chr>     <chr> <chr> <chr> <chr> <chr> <chr>  <int>     <int>
    #>  1 Pres… 0     19        <NA>  Iowa  Dona… Trump REP   R     896500         1
    #>  2 Pres… 0     19        <NA>  Iowa  Joe   Biden DEM   D     757780         0
    #>  3 Pres… 0     19        <NA>  Iowa  Jo    Jorg… LIB   O      19656         0
    #>  4 Pres… 0     19        <NA>  Iowa  Kanye West  IND   O       3202         0
    #>  5 Pres… 0     19        <NA>  Iowa  Howie Hawk… GRN   O       3071         0
    #>  6 Pres… 0     19        <NA>  Iowa  Don   Blan… CST   O       2303         0
    #>  7 Pres… 0     19        <NA>  Iowa  <NA>  Writ… WRI   O       2268         0
    #>  8 Pres… 0     19        <NA>  Iowa  Rocky De L… ALI   O       1081         0
    #>  9 Pres… 0     19        <NA>  Iowa  Brock Pier… IND   O        556         0
    #> 10 Pres… 0     19        <NA>  Iowa  Rick… King  OTH   O        551         0
    #> # … with 24 more rows, and 1 more variable: mpc <int>

<sup>Created on 2020-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by kjhealy** [comment]
Either that or your `colspec` is incorrect. It's missing `fips5` and the order of columns isn't the same as in the dataset. If you just run `read_csv()` without a colspec it'll guess correctly in this case.
