### ISSUE TITLE
Four bad rows

### ISSUE THREAD

**Issue by davidkane9** [kjhealy/us_elections_2020_csv#6]
There are four bad rows in the data.

``` r
library(tidyverse)

read_csv("https://raw.githubusercontent.com/kjhealy/us_elections_2020_csv/master/results_x2020_11_07_15_18_17.csv") %>% 
  filter(id %in% c("Iowa", "Ohio", "Utah")) %>% 
  select(1:4)
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   race = col_character(),
#>   id = col_character(),
#>   fips_char = col_character(),
#>   fips5 = col_character(),
#>   place = col_character(),
#>   fname = col_character(),
#>   lname = col_character(),
#>   party = col_character(),
#>   pab = col_character(),
#>   votes = col_double(),
#>   incumbent = col_double(),
#>   mpc = col_double()
#> )
#> # A tibble: 4 x 4
#>   race     id    fips_char fips5
#>   <chr>    <chr> <chr>     <chr>
#> 1 Governor Iowa  19        <NA> 
#> 2 Senate   Ohio  39        <NA> 
#> 3 Governor Ohio  39        <NA> 
#> 4 Senate   Utah  49        <NA>
```

<sup>Created on 2020-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There should not be a state name in the id column. Also, at least some of these elections did not happen this year. That is, there was no election for governor in Iowa, for example.

Apologies for not making this report more clear in my previous submission.

**Comment by kjhealy** [comment]
Oh I see what the problem is. The scraper was pulling the wrong column (`place` instead of `id`) for those cases, which as you say are ones where specific races (e.g. Governor) aren't happening. I'll update the csv momentarily. My mistake.
